---
- name: Make sure stack directory is present
  file:
    path: /srv/vsevoland
    state: directory

- name: Deploy environment file
  template:
    src: templates/vsevoland.env.j2
    dest: /srv/vsevoland/env

- name: Deploy the stack
  docker_stack:
    name: vsevoland
    resolve_image: never
    with_registry_auth: true
    compose:
      - version: '3.6'
        x-deploy-options: &deploy
          update_config:
            parallelism: 2
            delay: 3s
            failure_action: rollback
            order: start-first

        x-defaults: &defaults
          env_file:
            - /srv/vsevoland/env

          networks:
            - stacknet

        services:
          frontend:
            image: vsevolodskripnik/vsevoland-frontend
            environment:
              DOMAIN_NAME: "{{ domain_name }}"
            networks:
              - stacknet
              - traefiknet
            deploy:
              <<: *deploy
              replicas: 2
              labels:
                  - "traefik.enable=true"
                  - "traefik.port=3000"
                  - "traefik.common.frontend.rule=Host:{{ domain_name }}"
                  - "traefik.azure.frontend.rule=Host:{{ domain_name }};Path:/.well-known/microsoft-identity-association.json"
                  - "traefik.azure.frontend.headers.customResponseHeaders=Content-Type:application/json||Content-Length:112"
                  - "traefik.docker.network=traefiknet"

            networks:
              - stacknet
              - traefiknet

            deploy:
              labels:
                  - "traefik.enable=true"
                  - "traefik.port=5555"
                  - "traefik.frontend.rule=Host:{{ domain_name }}; PathPrefixStrip:/flower"
                  - "traefik.docker.network=traefiknet"

        networks:
          stacknet:
            driver: overlay

          traefiknet:
            external: true
