---
- name: Make sure CI account is added
  user:
    name: circle
    groups: "root, sudo, {{ app_group }}, docker"
    shell: /bin/bash

- name: Make sure CI ssh keys are present
  authorized_key:
    user: circle
    key: "{{ ci_key }}"

- name: Make sure CI user is able to access docker registry
  become: yes
  become_user: circle
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
