---
- name: Make sure swarm is initialized
  docker_swarm:
    state: present
    advertise_addr: "{{ swarm_manager_address }}"
    listen_addr: "{{ swarm_manager_address }}"

- name: Log in to the hub.docker.com
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
