---
- name: Make sure swarm is initialized
  docker_swarm:
    state: present
    advertise_addr: "eth1"
    listen_addr: "eth1"

- name: Log in to the hub.docker.com
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
